# Реализовать прототип с применением пакета tk. Получить максимально приближенный интерфейс
from tkinter import *
from tkinter.font import BOLD
from tkinter.ttk import Combobox
root = Tk()
var = IntVar()
var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
root.title('Создание аккаунта')
root.geometry('973x846')
root.configure(bg='white')
Label(text="Create an account *", bg='white', width=25, fg='black', font=('arial', 15, BOLD)).place(x=30, y=30)
Label(text="Please complete all fields *", bg='white', width=25, fg='black', font=('arial', 15)).place(x=68, y=60)
Label(text="First name *", bg='white', width=25, fg='black', font='arial 11').place(x=24, y=110)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=99, y=140)
Label(text="Last name *", width=25, bg='white', fg='black', font='arial 11').place(x=422, y=110)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=500, y=140)
Label(text="Job Title *", bg='white', width=25, fg='black', font='arial 11').place(x=14, y=190)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=99, y=220)
Label(text="Email *", bg='white', width=25, fg='black', font='arial 11').place(x=407, y=190)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=500, y=220)
Label(text="Password *", bg='white', width=25, fg='black', font='arial 11').place(x=20, y=270)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=99, y=300)
Label(text="Re-enter Password *", bg='white', width=25, fg='black', font='arial 11').place(x=453, y=270)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=500, y=300)
Label(text="Phone *", bg='white', width=25, fg='black', font='arial 11').place(x=8, y=350)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=99, y=380)
Label(text="Company *", bg='white', width=25, fg='black', font='arial 11').place(x=420, y=350)
Entry(width=25, bd=1, bg='white', font='arial 15').place(x=500, y=380)
Label(text="Employees *", bg='white', width=25, fg='black', font='arial 11').place(x=24, y=430)
Combobox(root, width=43, values=(['Yes', 'No'])).place(x=99, y=460)
Label(text="Country *", bg='white', width=25, fg='black', font='arial 11').place(x=414, y=430)
Combobox(root, width=43, values=(['Russia', 'USA', 'Brazil', 'Argentina', 'France'])).place(x=500, y=460)
Checkbutton(text="I give consent to receiving text messages (carrier charges may apply)", bg='white', variable=var1).place(x=95, y=510)
Checkbutton(text="I accept the Terms of Use", bg='white', variable=var2).place(x=95, y=530)
Button(width=40, height=2, text="Sign up", bg='dodger blue').place(x=95, y=560)


root.mainloop()